few changes, logs

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,14 +1,10 @@
 #!/bin/bash
 
-set -o errexit
-set -o nounset
-set -o pipefail
-
 OS="$(uname -s)"
 case "$OS" in
     Linux*)     os="linux";;
     Darwin*)    os="darwin";;
-    *)          echo "Unsupported OS: $OS" >&2; exit 1;;
+    *)          echo "Unsupported os: $OS"; exit 1;;
 esac
 
 RELEASE="${ASDF_INSTALL_VERSION}"
@@ -19,53 +15,91 @@ TEMP_FILE="$TEMP_DIR/$ASSET_NAME"
 
 trap 'rm -rf "${TEMP_DIR}"' EXIT
 
-error_exit() {
-  echo "$1" >&2
-  exit "${2:-1}"
-}
+export ASSET_RELEASE="$RELEASE"
 
-PAT="${PAT:-}" # Ensure PAT is initialized
-HEADER_ARGS=()
-if [ -n "$PAT" ]; then
-    HEADER_ARGS+=("-H" "Authorization: token $PAT")
+export PAT="${PAT:-""}"
+export OWNER='neuroactivos'
+export REPO='ac3p-workspace'
+
+if test -n "$PAT"
+then
+	export PAT_HEADER='-H "Authorization: token '"$PAT"'"'
 fi
 
-OWNER='neuroactivos'
-REPO='ac3p-workspace'
 RELEASES_BASE_URL="https://api.github.com/repos/$OWNER/$REPO/releases"
 
-R_T="${RELEASE:-latest}"
-RELEASE_INFO_URL="$RELEASES_BASE_URL/${R_T/tags\//}"
-RELEASE_DATA=$(curl -s "${HEADER_ARGS[@]}" -H "Accept: application/vnd.github.v3+json" "$RELEASE_INFO_URL")
+if test -z "$ASSET_RELEASE"
+then
+	export R_T="latest"
+	# Get the latest release tag
+	R_REL="$(curl -s $PAT_HEADER \
+	     -H "Accept: application/vnd.github.v3+json" \
+	     "$RELEASES_BASE_URL/${R_T}" | jq -r '"\(.id) \(.tag_name)"')"
 
-R_ID=$(echo "$RELEASE_DATA" | jq -r '.id')
-R_TAG=$(echo "$RELEASE_DATA" | jq -r '.tag_name')
-
-if [ -z "$R_ID" ] || [ -z "$R_TAG" ]; then
-    error_exit "ERROR: failed to get release data"
-fi
-
-mkdir -p "$INSTALL_PATH"
-
-ASSET_DOWNLOAD_URL="$RELEASES_BASE_URL/$R_ID/assets"
-ASSET_ID=$(curl -s -L "${HEADER_ARGS[@]}" -H "Accept: application/vnd.github+json" \
-            "$ASSET_DOWNLOAD_URL" | jq -r --arg NAME "$ASSET_NAME" '.[] | select(.name == $NAME) | .id')
-
-if [ -z "$ASSET_ID" ]; then
-    error_exit "ERROR: failed to get the asset id from the release asset data"
-fi
-
-ASSET_DOWNLOAD_URL="$RELEASES_BASE_URL/assets/$ASSET_ID"
-
-echo "Installing asset $ASSET_NAME from release $R_TAG into $INSTALL_PATH/$ASSET_NAME"
-
-if curl -s -S -L "${HEADER_ARGS[@]}" -H "Accept: application/octet-stream" \
-     -o "$TEMP_FILE" \
-     "$ASSET_DOWNLOAD_URL"; then
-    mv "$TEMP_FILE" "$INSTALL_PATH/$ASSET_NAME"
-    chmod +x "$INSTALL_PATH/$ASSET_NAME"
-    asdf reshim ac3p "$RELEASE"
 else
-    error_exit "ERROR: failed to download the asset"
+	R_T="$ASSET_RELEASE"
+	# Get the release tag
+	R_REL="$(curl -s $PAT_HEADER \
+	     -H "Accept: application/vnd.github.v3+json" \
+	     "$RELEASES_BASE_URL/tags/${R_T}" | jq -r '"\(.id) \(.tag_name)"')"
+fi
+
+
+if test -z "$R_REL"
+then
+	echo "ac3p: error: failed to get release data" 1>&2
+	exit 1
+fi
+
+R_TAG="${R_REL##* }"
+R_ID="${R_REL%% *}"
+
+if test -z "$R_TAG"
+then
+	echo "ac3p: error: failed to get the release tag" 1>&2
+	exit 1
+fi
+
+if test -z "$R_ID"
+then
+	echo "ac3p: error: failed to get the release id" 1>&2
+	exit 1
+fi
+
+TARGET_DIR="$INSTALL_PATH" 
+mkdir -p "$TARGET_DIR/"
+
+export ARTIFACT_NAME="$ASSET_NAME"
+export OUTPUT_FILENAME="$TARGET_DIR/ac3p"
+
+export ASSET_DOWNLOAD_URL="$RELEASES_BASE_URL/$R_ID/assets"
+
+#echo "downloading asset $ARTIFACT_NAME data for $R_TAG from $ASSET_DOWNLOAD_URL"
+
+# Download the asset info
+ASSET_ID="$(curl -s -L $PAT_HEADER -H "Accept: application/vnd.github+json" \
+	"$ASSET_DOWNLOAD_URL" | jq -r --arg NAME "$ARTIFACT_NAME" '.[] | select(.name == $NAME) | .id')"
+
+if test -z "$ASSET_ID"
+then
+        echo "ac3p: error: failed to get the asset id from the release asset data" 1>&2
+        exit 1
+fi
+
+export ASSET_DOWNLOAD_URL="$RELEASES_BASE_URL/assets/$ASSET_ID"
+
+#echo "downloading $ARTIFACT_NAME from $ASSET_DOWNLOAD_URL"
+echo "ac3p: installing asset $ARTIFACT_NAME from release $R_TAG into $OUTPUT_FILENAME"
+
+# Download the asset info
+if curl -s -S -L $PAT_HEADER -H "Accept: application/octet-stream" -o "$TEMP_FILE" "$ASSET_DOWNLOAD_URL" 
+then
+    mv "$TEMP_FILE" "$OUTPUT_FILENAME"
+    chmod +x "$OUTPUT_FILENAME"
+    echo "ac3p: asdf reshim ac3p $RELEASE"
+    asdf reshim ac3p "$RELEASE" && ac3p -version
+else
+        echo "ac3p: error: failed to download" 1>&2
+        exit 1
 fi
 
